name: Python

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        id: display-version
        run: |
          python -c "import sys; print(sys.version)"
          echo "::set-output name=python-version::${{ steps.display-version.outputs.stdout }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-version
          path: ${{ github.workspace }}/python-version.txt
