name: Python

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Save Python version to file
        run: echo "${{ matrix.python-version }}" > ${{ github.workspace }}/python-version-${{ matrix.python-version }}.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-versions
          path: ${{ github.workspace }}/python-version-*.txt
